[package]
name = "polymodo"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "cli-gen"]
resolver = "3"

[dependencies]
log = "0.4"
log-panics = "2.1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1.0.95"
derive_more = { version = "2.0.1", features = ["display", "error", "from"] }
strum = { version = "0.27.1", features = ["derive"] }
tokio = { version = "1", features = ["rt", "sync", "net", "time", "macros", "io-util"] }

# CLI
clap = { version = "4.5", features = ["derive"] }

# Windowing
smithay-client-toolkit = { version = "0.19.2", default-features = false, features = ["xkbcommon"] }
wayland-backend = { version = "0.3", features = ["client_system", "dlopen"] }
wayland-protocols = { version = "0.32.6", features = ["staging"] }
wgpu = "24.0.1"
egui = "0.31.0"
egui-wgpu = "0.31.0"
egui_extras = { version = "0.31.1", features = ["file", "image", "svg"] }
image = { version = "0.25", features = ["jpeg", "png"] }

# Launcher
nix = { version = "0.30.1", features = ["process"] }
xdg = "3.0.0"
rust-ini = "0.21.1"
nucleo = "0.5.0"
fork = "0.2.0"
smallvec = "1.14.0"
rand = "0.9.0"
local-channel = "0.1.5"
bincode = "2.0.1"
walkdir = "2.5.0"
icon = "0.1.2"
