import { Button, VerticalBox, LineEdit, Palette, ListView, StandardListView } from "std-widgets.slint";
import { PolymodoTextInput } from "text-input.slint";
import { LauncherEntry, LauncherEntries, LauncherListView } from "launcher-entry.slint";

export { LauncherEntries }

export global LauncherSearch {
    callback search-edited(/*query*/ string);
}

export component LauncherWindow inherits Window {
    in property <length> font-size: 18px;

    callback escape-pressed();
    callback launch(/*index*/ int);

    background: transparent;
    default-font-size: font-size;
    no-frame: true;

    title: "launcher";
    width: 450px;
    height: 581px;

    init => {
        Palette.color-scheme = ColorScheme.dark;
    }

    background := Rectangle {
        width: 100%;
        height: 100%;
        background: #000000cc;

        border-radius: 12px;
        border-color: darkgrey;
        border-width: 1px;
    }

    VerticalBox {
        vertical-stretch: 1;
        spacing: 0;

        search_box := PolymodoTextInput {
            vertical-stretch: 0;

            init => {
                self.focus-input();
            }

            key-pressed(event) => {
                if (event.text == Key.DownArrow) {
                    list_view.set-current-item-next();
                    return accept;
                } else if (event.text == Key.UpArrow) {
                    list_view.set-current-item-previous();
                    return accept;
                } else if (event.text == Key.Escape) {
                    escape-pressed();
                    return accept;
                } else if (event.text == Key.Return) {
                    launch(list_view.current-item);
                    return accept;
                }

                reject
            }

            text-edited => {
                LauncherSearch.search-edited(self.text);
            }
        }

        Rectangle {
            vertical-stretch: 1;

            list_view := LauncherListView {
                model: LauncherEntries.entries;
                current-item: 0;

                if LauncherEntries.entries.length == 0: Text {
                    text: "No results";
                }
            }
        }
    }
}
