import { Button, VerticalBox, LineEdit, Palette, ListView, StandardListView } from "std-widgets.slint";
import { PolymodoTextInput } from "text-input.slint";
import { LauncherEntry, LauncherEntries } from "launcher-entry.slint";

export { LauncherEntries }

export global LauncherSearch {
    callback search-edited(/*query*/ string);
}

export component MainWindow inherits Window {
    in property <length> font-size: 18px;

    background: transparent;
    default-font-size: font-size;
    no-frame: true;

    title: "launcher";
    width: 400px;
    height: 600px;

    init => {
        Palette.color-scheme = ColorScheme.dark;
    }

    background := Rectangle {
        width: 100%;
        height: 100%;
        background: #000000cc;

        border-radius: 12px;
        border-color: darkgrey;
        border-width: 1px;
    }

    VerticalBox {
        vertical-stretch: 1;
        spacing: 0;

        search_box := PolymodoTextInput {
            vertical-stretch: 0;

            init => {
                self.focus-input();
            }

            text-edited => {
                LauncherSearch.search-edited(self.text);
            }
        }

        Rectangle {
            vertical-stretch: 1;

            if LauncherEntries.entries.length == 0: Text {
                text: "No results";
            }

            if LauncherEntries.entries.length != 0: ListView {
                for item[index] in LauncherEntries.entries: LauncherEntry {
                    width: parent.width;
                    name: item.name;
                    icon: item.icon;
                }
            }
        }
    }
}
